# RecBole 用 config ファイル

## general
gpu_id: 0
use_gpu: False  # GPUを使う時はTRUEにする
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'  # 使うデータが格納されている場所
checkpoint_dir: 'saved/'  # モデル保存先
show_progress: True
save_dataset: False  # True にすればtrain, valid, test で使ったデータを保存してくれる
save_dataloaders: False

## Data Settings
# ref: https://recbole.io/docs/v1.0.0/user_guide/config/data_settings.html#data-settings

### Atomic File Format
field_separator: "\t"
seq_separator: "@" # 文字列があった場合この文字で区切られる。特徴量読み込み時にバグってしまう可能性があるため、できるだけデータを事前に処理しておき絶対に出現しない保障が取れている記号を書くべき(日本語の場合)

### Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: ~  # implicit feedback の場合
TIME_FIELD: timestamp

### Selectively Loading
# 使うデータだけを選んで loadします
load_col:
    inter: [user_id, item_id, timestamp, weather_id, precipitation]
    user: [user_id, feature1, feature2]
    item: [item_id, item_name, item_category_id]
unused_col:  # データとしては読み込むけど学習には使いたくないカラムはここで指定する
    inter: [timestamp, precipitation]

### Preprocessing
normalize_all: True  # float 型のカラムをすべて normalize する

## Training and evaluation config
# ref: https://recbole.io/docs/user_guide/train_eval_intro.html#training-evaluation-introduction
epochs: 50
stopping_step: 10  # 10 step valid_metric が改善しない場合は止める
train_batch_size: 4096
eval_batch_size: 4096
neg_sampling:  # implicit feedbackなデータを扱っていて positive,negative両方のラベルが必要な手法を試す際に、negative samplingすることでデータを用意できる
    uniform: 1

eval_args:
    group_by: user  # user 単位でアイテムを集約して評価に使う。基本的にこれ以外使うことはない
    order: TO  # Temporal Order。時系列順で train, valid, test を分けてくれる
    split: {'RS': [0.8,0.1,0.1]}  # 80%, 10%, 10% で分けてくれる
    mode: uni001  # 1つのポジティブサンプルにつき、いくつのネガティブサンプルをどんな分布から何回行うか. uni001 は一様分布から1回行うの意. pop001 なども使える.

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 5
valid_metric: Recall@5  # この指標をtrackする
metric_decimal_place: 4
